---
- include_vars:
    file: "../vault/secrets.yml"
    name: vault

- name: Get container ip
  shell:
    cmd: "podman inspect -f {% raw %}'{{.NetworkSettings.IPAddress}}'{% endraw %} {{container_name}}"
  args:
    executable: /bin/bash
  register: container_ip


#Add the main DNS record
- name: "Add or modify POD {{container_name}} A to {{container_ip.stdout}}"
  nsupdate:
    key_algorithm: "hmac-sha512"
    key_name: "{{vault.homedns_key_name}}"
    key_secret: "{{vault.homedns_key_secret}}"
    server: "{{homedns_server}}"
    zone: "{{my_domain}}"
    record: "{{container_name}}"
    value: "{{container_ip.stdout}}"
    ttl: 300
    type: "A"
  when: container_ip is defined and container_ip.rc == 0


- name: "Add or modify {{ container_ip.stdout | ipaddr('revdns') }} PTR to {{container_name}}.{{my_domain}}"
  nsupdate:
    key_algorithm: "hmac-sha512"
    key_name: "{{homedns_key_name}}"
    key_secret: "{{homedns_key_secret}}"
    server: "{{homedns_server}}"
    record: "{{container_ip.stdout | ipaddr('revdns')}}"
    type: "PTR"
    value: "{{container_name}}.{{my_domain}}."
    ttl: 3600
    zone: 10.in-addr.arpa
    state: present
  when: container_ip is defined and container_ip.rc == 0

#Make a CNAME in the pod subdomain
- name: "Add or modify {{container_name}} A to {{ansible_default_ipv4.address}}"
  nsupdate:
    key_algorithm: "hmac-sha512"
    key_name: "{{vault.homedns_key_name}}"
    key_secret: "{{vault.homedns_key_secret}}"
    server: "{{homedns_server}}"
    zone: "{{my_domain}}"
    record: "{{container_name}}.pod"
    value: "{{container_name}}.{{my_domain}}."
    ttl: 3600
    type: "CNAME"
